name: Semantic Release

on:
  push:
    branches:
      - main  # ou a branch principal do seu repositório

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use a versão do Node.js que você precisa

      - name: Install dependencies
        run: npm install

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git

      - name: Run semantic-release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso do GitHub (já vem configurado no repositório)
